---
framework: mocha 

preRun:
  command:
    - npm install

postMerge:
# These would be the glob patterns for the test cases that you want to execute in the post-merge jobs. A postMerge test execution job is initiated whenever a PR is merged into a branch.
  pattern:
    - "./test/**/*.js"
preMerge:
  pattern:
    - "./test/**/*.js"
configFile: mocha.opts
version : 1.0.1
